name: Merge PR

on:
    pull_request:
        types:
            - closed
        branches:
            - main

concurrency:
    group: merge
    cancel-in-progress: false

jobs:
    merge:
        name: Merge PR
        runs-on: self-hosted-hoprnet-small
        if: github.event.pull_request.merged == true

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup GCP
              id: gcp
              uses: hoprnet/hopr-workflows/actions/setup-gcp@master
              with:
                  google-credentials: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
                  login-artifact-registry: 'true'

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  driver: kubernetes

            - name: Build and push docker image
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: ${{ vars.DOCKER_IMAGE_REGISTRY }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
